eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
spring.boot.admin.client.url=http://localhost:9999
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
