eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.instance-id=${spring.application.name}:${random.value}


#admin-server-client-config
spring.boot.admin.client.url=http://localhost:9999
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

#config-server-client-config
spring.config.import=optional:configserver:http://localhost:8888
